### ISSUE TITLE
adding more keys

### ISSUE THREAD

**Issue by patvdleer** [jeroen94704/klepcbgen#11]
As I'm looking for a "regular" keyboard with extra keys I was hoping to use this to generate the PCB. Now I'm guessing the 104 keys aren't feasible due to limited I/O of the 32u4. Would using a 74HCxxx multiplexer fix this issue or as a complete alternative, a RP2040?

**Comment by Alan-JH** [comment]
If you matrix them perfectly, you can get up to 156 keys out of the 25 i/o on the 32u4 (12 rows, 13 columns or vice versa). klepcbgen seems to be limited to 7 rows and 18 columns, but that still leaves you 126 keys in theory. In practice, the limit it can generate is likely less due to nonstandard spacing, but you can still get more than enough keys if you get creative with your matrixing.
