### ISSUE TITLE
.sch fails to open due to blank line

### ISSUE THREAD

**Issue by rastersoft** [jeroen94704/klepcbgen#15]
Hi:

I created a layout and exported as JSON, and then applied your program to generate the KiCad files. But when I try to open it in the current KiCad version, it reports an error in a line (it varies depending on the layout). Opening the .sch file with a text editor shows that in the specified line there is a blank line. Manually removing that line makes the file work.

**Comment by jeroen94704** [comment]
Awesome, that's a great find! Fixed in the latest commit. As an aside, for now you'll have to replace the footprints for the SMD capacitors and resistors manually in Kicad 6:

Capacitor_SMD:C_0805_2012Metric_Pad1.15x1.40mm_HandSolder -> Capacitor_SMD:C_0805_2012Metric_Pad1.18x1.45mm_HandSolder

and 

Resistor_SMD:R_0805_2012Metric_Pad1.15x1.40mm_HandSolder -> Resistor_SMD:R_0805_2012Metric_Pad1.20x1.40mm_HandSolder
